#Finds motifs in a DNA sequence

def motifcomb(string, kmer):
	lenKmer = len(kmer)
	locations = []
	for i in range(len(string) - lenKmer):
		if kmer == string[i:i + lenKmer]:
			locations.append(i + 1)

	answer = ""
	for i in locations:
		answer += str(i) + " "

	return answer[:-1]

#Assertion to check the function
string = "AGATAATAGGCTGGTATAATAGGTAATAGGGGATAATAGGGCGATCTAATAGGACTATAATAGGCTTATGCTAATAGGTAATAGGTGCCCCGTAATAGGATCCTAATAGGTAATAGGGTCTAATAGGGATTTCTAATAGGTAATAGGTAATAGGATTAATAGGTAATAGGTTCTAATAGGTAATAGGGTAATAGGAGTCTGTGTGACTAATAGGCTAATAGGTAATAGGTTCTAATAGGCTTAATAGGCTAATAGGCTAATAGGTAATAGGATATAATAGGGCGGGTAATAGGTATTAATAGGTTTAATAGGTCTAATAGGGATAATAGGTAATAGGGCTAATAGGGTAATAGGCTCGCTAATAGGCGTAATAGGGTAATAGGTAATAGGTAATAGGTAATAGGATTCTAATAGGTAATAGGCTGATAATAGGCTAATAGGGTAATAGGGTAATAGGTAATAGGTAGCTAATAGGCGGCTAATAGGGTAATAGGGTAATAGGGGTTAATAGGGCTAATAGGTAATAGGTTGGTTAATAGGTAATAGGGTAATAGGTAATAGGGCCATAACGTAATAGGGTCTAATAGGTCTAATAGGCATAATAGGTAATAGGTAATAGGTCCATAATAGGTAATAGGTAATAGGTAATAGGGTAATAGGCCTAATAGGAGGTAATAGGTAATAGGCAGAATAATAGGGTAATAGGGTTAATAGGGGTAATAGGTAATAGGGATAATAGGGGCCTAATAGGGCCTAATAGGTAATAGGTAATAGGCCGCTAATAGGTAATAGGGCCTTAATAGGTAACTTTAATAGGTGAGCTTAATAGGGGGGAGCCGTTAATAGGGGGTAATAGGAAAGAATTAATAGGTAATAGGCTAATAGGTTAATAGGCTAATAGGGGTAATAGGCTTAATAGGACTAATAGGGAATGAATAATAGGTTGCGTAATAGG"
kmer = 'TAATAGGTA'
assert(motifcomb(string,kmer)) == '17 72 104 134 141 157 174 216 258 287 324 377 384 391 409 451 458 515 534 549 600 607 625 632 639 673 718 755 762 780 798 865'